### ISSUE TITLE
feature request: an `is_sanitized` function that checks if the given path is sanitized or not

### ISSUE THREAD

**Issue by SeriousBug** [kardeiz/sanitize-filename#2]
I'm looking for:

```rust
pub fn is_sanitized<S: AsRef<str>>(name: S) -> bool;
```

This function would return true if calling `sanitize` would be a no-op for this path, that the path is fully sane. There also should be a `is_sanitized_with_options` to mirror the same interface.

I'm happy to contribute this change if you'd like to see it in the crate, please let me know.

**Comment by kardeiz** [comment]
Hi @SeriousBug , that sounds like a good addition, and I would be happy to accept/merge your contribution!
