### ISSUE TITLE
source code in crate should not be executable

### ISSUE THREAD

**Issue by werdahias** [kardeiz/sanitize-filename#4]
Hi. I'm in the process of packaging your crate for debian. I noticed the following lintian warnings:
```

librust-sanitize-filename-dev: executable-not-elf-or-script usr/share/cargo/registry/sanitize-filename-0.4.0/.gitignore
librust-sanitize-filename-dev: executable-not-elf-or-script usr/share/cargo/registry/sanitize-filename-0.4.0/README.md
librust-sanitize-filename-dev: executable-not-elf-or-script usr/share/cargo/registry/sanitize-filename-0.4.0/src/lib.rs
librust-sanitize-filename-dev: executable-not-elf-or-script usr/share/cargo/registry/sanitize-filename-0.4.0/src/main.rs
```

This translates that the files above are probably marked as executable (chmod +x). Please have a look at it.

**Comment by dkg** [comment]
Looking at the repo, the files in question aren't executable in git.  So something unusual is happening in how the crate gets created from the git repo, that you probably want to fix.
