### ISSUE TITLE
Trailing dot character

### ISSUE THREAD

**Issue by ndtoan96** [kardeiz/sanitize-filename#7]
On Windows, supposed I create a file with name `some_file...`. There's no error but `some_file` is created instead, so when I try to access `some_file...`, I get an error.

For that reason, I think this library should remove trailing `.` too, at least on Windows.

**Comment by kardeiz** [comment]
@ndtoan96 Thanks for the issue! You are completely right: this is definitely a bug. It looks like I accidentally re-used the value for RESERVED_RE in WINDOWS_TRAILING_RE. I'll replace the regex and push a new minor version tomorrow.
