### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by molenick** [kardeiz/sanitize-filename#8]
Hi, I'm looking at doing some cross-platform file sanitization and came across your crate.  It looks good, has tests and is pretty clear what it's doing - awesome stuff!

Unfortunately, I noticed that the crate currently doesn't have a license.  Would you be open to adding a license to this project to clarify how it can be used?

**Comment by kardeiz** [comment]
Sure, I've merged your PR. I am not a lawyer, but I guess I always thought `license = "MIT"` in the Cargo.toml was a valid license declaration...

**Comment by molenick** [comment]
Ah yea, missed the declaration in the toml.  Thanks!
